mybatis:
  mapper-locations: class-path:*.xml
  type-aliases-package: com.hzl.demo.pojo
spring:
  datasource:
    data-username: root
    data-password: hzl=19930515
    url: jdbc:mysql://localhost:3306/test/useUnicode=true&CharacterEncodeing=utf8&useSSl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1119641581@qq.com
    password: gasttegpaohybagj
    default-encoding: utf-8
  thymeleaf:
    cache: false #关闭缓存，及时刷新,生产环境一般设置为true
 #   prefix: /templates
 #   suffix: .html
#    encoding: UTF-8
 #   servlet:
 #    mode: HTML5
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
#    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
#server:
#  port: 8088
# servlet:
#   context-path: /sb #指定上下文
#  session:
##     timeout: 60m    #session过期时间